### ISSUE TITLE
Location of temporary directory must not be assumed

### ISSUE THREAD

**Issue by kitsunenokenja** [ddymko/crouton#1]
Browsing your code, I spotted some bad practice. You shouldn't ever hard-code /tmp. You don't know where the working temporary directory resides on the file system at runtime. PHP has built-in functions for determining the operating system's directory for this, or you can use something like tempnam() to obtain a handle to a temporary file without caring where exactly it resides.

Also check if the SPL file object is suitable which may be convenient. I considered using it but there is a minor limitation to it that caused me to make my own class wrapping tempnam().

On the topic of file system access there is also an fopen call without any kind of error checking, but that'd be a different issue.

**Comment by ddymko** [comment]
@kitsunenokenja 

Thanks for your input and you are right hardcoding /tmp is bad practice [example a](https://github.com/ddymko/crouton/blob/master/src/FileSystem.php#L11)

That being said this is not a finished product =D . I am working on this piece of by piece so this is far from a finished product. The end product will specifically work with the /etc/cron (the assumption that this is being run on a *nix machine). The user will specify what the name of the script that would like to run in - which will then be logically checked to see if it exists. If the file does not exist then we could throw and error and prevent writing to the cron. I am also considering allowing a config file where the user may put in some configs that meet their needs.

What you are currently viewing is a project that has just been started and not polished or finished. To justify the reason as to why I am hardcoding file paths is to please the current CI and unit tests. Also note [example b](https://github.com/ddymko/crouton/blob/master/src/Crouton.php#L29), while not the prettiest thing I have this conditional here to prevent the CI or unit tests from freaking out.

I appreciate your input and I hope this will help you understand that this is far from done and is currently a placeholder. I would love to get your input on the final product though!
